/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          primary: 'hsl(var(--bg-primary))',
          surface: 'hsl(var(--bg-surface))',
          section: 'hsl(var(--bg-section))',
        },
        'stroke-grey': {
          primary: 'hsl(var(--stroke-grey-primary))',
          secondary: 'hsl(var(--stroke-grey-secondary))',
        },
        warning: {
          text: 'hsl(var(--warning))',
          bg: 'hsl(var(--warning-bg))',
          border: 'hsl(var(--warning-border))',
        },
        slippage: {
          'warning-bg': 'hsl(var(--slippage-warning-bg))',
          'warning-text': 'hsl(var(--slippage-warning-text))',
          'error-bg': 'hsl(var(--slippage-error-bg))',
          'error-text': 'hsl(var(--slippage-error-text))',
        },
        icon: {
          primary: 'hsl(var(--icon-primary))',
          subtle: 'hsl(var(--icon-subtle))',
          disabled: 'hsl(var(--icon-disabled))',
        },
        state: {
          error: {
            default: 'hsl(var(--state-error-default))',
          },
          subtle: 'hsl(var(--icon-subtle))',
          disabled: 'hsl(var(--icon-disabled))',
          highlight: {
            light: 'hsl(var(--state-highlight-light))',
          },
        },
        background: 'hsl(var(--background))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: 'hsl(var(--primary-50))',
          100: 'hsl(var(--primary-100))',
          200: 'hsl(var(--primary-200))',
          300: 'hsl(var(--primary-300))',
          400: 'hsl(var(--primary-400))',
          500: 'hsl(var(--primary-500))',
          600: 'hsl(var(--primary-600))',
          700: 'hsl(var(--primary-700))',
          800: 'hsl(var(--primary-800))',
          900: 'hsl(var(--primary-900))',
          950: 'hsl(var(--primary-950))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50: 'hsl(var(--secondary-50))',
          100: 'hsl(var(--secondary-100))',
          200: 'hsl(var(--secondary-200))',
          300: 'hsl(var(--secondary-300))',
          400: 'hsl(var(--secondary-400))',
          500: 'hsl(var(--secondary-500))',
          600: 'hsl(var(--secondary-600))',
          700: 'hsl(var(--secondary-700))',
          800: 'hsl(var(--secondary-800))',
          900: 'hsl(var(--secondary-900))',
          950: 'hsl(var(--secondary-950))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
          50: 'hsl(var(--accent-50))',
          100: 'hsl(var(--accent-100))',
          200: 'hsl(var(--accent-200))',
          300: 'hsl(var(--accent-300))',
          400: 'hsl(var(--accent-400))',
          500: 'hsl(var(--accent-500))',
          600: 'hsl(var(--accent-600))',
          700: 'hsl(var(--accent-700))',
          800: 'hsl(var(--accent-800))',
          900: 'hsl(var(--accent-900))',
          950: 'hsl(var(--accent-950))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--success-foreground))',
          50: 'hsl(var(--success-50))',
          100: 'hsl(var(--success-100))',
          200: 'hsl(var(--success-200))',
          300: 'hsl(var(--success-300))',
          400: 'hsl(var(--success-400))',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          700: 'hsl(var(--success-700))',
          800: 'hsl(var(--success-800))',
          900: 'hsl(var(--success-900))',
          950: 'hsl(var(--success-950))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--warning-foreground))',
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          700: 'hsl(var(--warning-700))',
          800: 'hsl(var(--warning-800))',
          900: 'hsl(var(--warning-900))',
          950: 'hsl(var(--warning-950))',
          bg: 'hsl(var(--warning-bg))',
          border: 'hsl(var(--warning-border))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
          foreground: 'hsl(var(--error-foreground))',
          50: 'hsl(var(--error-50))',
          100: 'hsl(var(--error-100))',
          200: 'hsl(var(--error-200))',
          300: 'hsl(var(--error-300))',
          400: 'hsl(var(--error-400))',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          700: 'hsl(var(--error-700))',
          800: 'hsl(var(--error-800))',
          900: 'hsl(var(--error-900))',
          950: 'hsl(var(--error-950))',
        },
        overlay: 'hsl(var(--overlay))',
        tertiary: 'hsl(var(--tertiary))',
        foreground: 'hsl(var(--foreground))',
        'muted-foreground': 'hsl(var(--muted-foreground))',
        border: 'hsl(var(--border))',
        active: 'hsl(var(--active))',
        'active-border': 'hsl(var(--active-border))',
        filled: 'hsl(var(--filled))',
        'scroll-bar': 'hsl(var(--scroll-bar))',
        'sec-border': 'hsl(var(--sec-border))',
        'black-medium': '#191919',
        light: '#FCFCFC',
        failed: 'hsl(var(--failed))',
        info: 'hsl(var(--info))',
        divider: 'hsl(var(--divider))',
        section: 'hsl(var(--section))',
        disabled: 'hsl(var(--disabled))',
        neutral: 'hsl(var(--neutral))',
        bar: 'hsl(var(--bar))',
        'footer-icons': 'hsl(var(--footer-icons))',
        'sec-btn': 'hsl(var(--sec-btn))',
        grey: {
          primary: 'hsl(var(--text-grey-primary))',
          secondary: 'hsl(var(--text-grey-secondary))',
          muted: 'hsl(var(--text-grey-muted))',
          disabled: 'hsl(var(--text-grey-disabled))',
          medium: '#666666',
        },
        static: {
          black: {
            DEFAULT: 'hsl(var(--base-static-black))',
            alpha: {
              10: 'hsl(var(--base-static-black) / 0.1)',
            },
          },
          white: {
            DEFAULT: 'hsl(var(--base-static-white))',
            alpha: {
              10: 'hsl(var(--base-static-white) / 0.1)',
            },
          },
        },
        // Legacy color mappings - can be removed if not used
        blue: {
          DEFAULT: 'hsl(var(--primary))',
          50: 'hsl(var(--primary-50))',
          100: 'hsl(var(--primary-100))',
          200: 'hsl(var(--primary-200))',
          300: 'hsl(var(--primary-300))',
          400: 'hsl(var(--primary-400))',
          500: 'hsl(var(--primary-500))',
          600: 'hsl(var(--primary-600))',
          alpha: {
            10: 'hsl(var(--primary) / 0.1)',
          },
        },
        green: {
          DEFAULT: 'hsl(var(--success))',
          50: 'hsl(var(--success-50))',
          100: 'hsl(var(--success-100))',
          200: 'hsl(var(--success-200))',
          300: 'hsl(var(--success-300))',
          400: 'hsl(var(--success-400))',
          500: 'hsl(var(--success-500))',
          600: 'hsl(var(--success-600))',
          alpha: {
            10: 'hsl(var(--success) / 0.1)',
          },
        },
        purple: {
          DEFAULT: 'hsl(var(--accent))',
          50: 'hsl(var(--accent-50))',
          100: 'hsl(var(--accent-100))',
          200: 'hsl(var(--accent-200))',
          300: 'hsl(var(--accent-300))',
          400: 'hsl(var(--accent-400))',
          500: 'hsl(var(--accent-500))',
          600: 'hsl(var(--accent-600))',
          alpha: {
            10: 'hsl(var(--accent) / 0.1)',
          },
        },
        red: {
          DEFAULT: 'hsl(var(--error))',
          50: 'hsl(var(--error-50))',
          100: 'hsl(var(--error-100))',
          200: 'hsl(var(--error-200))',
          300: 'hsl(var(--error-300))',
          400: 'hsl(var(--error-400))',
          500: 'hsl(var(--error-500))',
          600: 'hsl(var(--error-600))',
          alpha: {
            10: 'hsl(var(--error) / 0.1)',
          },
        },
        yellow: {
          DEFAULT: 'hsl(var(--warning))',
          50: 'hsl(var(--warning-50))',
          100: 'hsl(var(--warning-100))',
          200: 'hsl(var(--warning-200))',
          300: 'hsl(var(--warning-300))',
          400: 'hsl(var(--warning-400))',
          500: 'hsl(var(--warning-500))',
          600: 'hsl(var(--warning-600))',
          alpha: {
            10: 'hsl(var(--warning) / 0.1)',
          },
        },
      },
      borderRadius: {
        '32px': '32px',
      },
      keyframes: {
        loading: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        overlayShow: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        overlayHide: {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        dialogShow: {
          from: { opacity: '0', transform: 'translateY(16px) scale(0.95)' },
          to: { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        dialogHide: {
          from: { opacity: '1', transform: 'translateY(0) scale(1)' },
          to: { opacity: '0', transform: 'translateY(16px) scale(0.95)' },
        },
        slideInFromLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInFromRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-from-top': {
          from: { transform: 'translateY(4px) scale(0.97)', opacity: '0' },
          to: { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'slide-from-bottom': {
          from: { transform: 'translateY(-4px) scale(0.97)', opacity: '0' },
          to: { transform: 'translateY(0) scale(1)', opacity: '1' },
        },
        'slide-from-left': {
          from: { transform: 'translateX(4px) scale(0.97)', opacity: '0' },
          to: { transform: 'translateX(0) scale(1)', opacity: '1' },
        },
        'slide-from-right': {
          from: { transform: 'translateX(-4px) scale(0.97)', opacity: '0' },
          to: { transform: 'translateX(0) scale(1)', opacity: '1' },
        },
        'slide-to-right': {
          from: { transform: 'translateX(0) scale(1)', opacity: '1' },
          to: { transform: 'translateX(-4px) scale(0.97)', opacity: '0' },
        },
        'slide-to-top': {
          from: { transform: 'translateY(0) scale(1)', opacity: '1' },
          to: { transform: 'translateY(4px) scale(0.97)', opacity: '0' },
        },
        'slide-to-bottom': {
          from: { transform: 'translateY(0) scale(1)', opacity: '1' },
          to: { transform: 'translateY(-4px) scale(0.97)', opacity: '0' },
        },
        'slide-to-left': {
          from: { transform: 'translateX(0) scale(1)', opacity: '1' },
          to: { transform: 'translateX(4px) scale(0.97)', opacity: '0' },
        },
        'drawer-slide-to-right': {
          from: { transform: 'translateX(-100%)' },
          to: { transform: 'translateX(0)' },
        },
        'drawer-slide-to-left': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(-100%)' },
        },
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        slideDownAndFade: {
          from: { opacity: '0', transform: 'translateY(-2px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideLeftAndFade: {
          from: { opacity: '0', transform: 'translateX(2px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        slideUpAndFade: {
          from: { opacity: '0', transform: 'translateY(2px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideRightAndFade: {
          from: { opacity: '0', transform: 'translateX(-2px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        slideDown: {
          from: { height: '0', opacity: '0' },
          to: { height: 'var(--radix-collapsible-content-height)', opacity: '1' },
        },
        slideUp: {
          from: { height: 'var(--radix-collapsible-content-height)', opacity: '1' },
          to: { height: '0', opacity: '0' },
        },
      },
      animation: {
        overlayShow: 'overlayShow 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        overlayHide: 'overlayHide 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        dialogShow: 'dialogShow 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        dialogHide: 'dialogHide 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideDownAndFade: 'slideDownAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideLeftAndFade: 'slideLeftAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideUpAndFade: 'slideUpAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        slideRightAndFade: 'slideRightAndFade 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-top': 'slide-from-top 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-bottom': 'slide-from-bottom 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-left': 'slide-from-left 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-right': 'slide-from-right 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-to-top': 'slide-to-top 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-to-bottom': 'slide-to-bottom 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-to-left': 'slide-to-left 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-to-right': 'slide-to-right 150ms cubic-bezier(0.16, 1, 0.3, 1)',
        'drawer-slide-to-right': 'drawer-slide-to-right 600ms',
        'drawer-slide-to-left': 'drawer-slide-to-left 600ms',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-down': 'slideDown 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-up': 'slideUp 300ms cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionTimingFunction: {
        retro: 'cubic-bezier(0.2, 0.0, 0, 1.0)',
      },
    },
  },
  plugins: [],
};
